### ISSUE TITLE
Simplify all posts page for a quick overview

### ISSUE THREAD

**Issue by stefanv** [scientific-python/blog.scientific-python.org#130]
It would be great to be able to get a "bird's eye view" of all the blog posts ever made. Instead of paginating to 5 or 10, we can paginate to a hundred, and make the post list much more condensed (e.g., by removing the abstracts).

https://blog.scientific-python.org/posts/

**Comment by alphapapa** [comment]
<details><summary>WIP screenshot</summary>
<p>

![localhost_1313_posts_](https://github.com/scientific-python/blog.scientific-python.org/assets/601365/39260cbe-e769-4896-bf95-98ee284a271f)


</p>
</details>

**Comment by jarrodmillman** [comment]
@tupui Thoughts?

**Comment by tupui** [comment]
That's nice! Now the design seems a bit empty/white with the sidebar (I am not a UI designer though), but that can be for a follow up.

**Comment by alphapapa** [comment]
@tupui Agreed that the sidebar feels a bit empty.  We're discussing some changes to the tag cloud in https://github.com/scientific-python/scientific-python-hugo-theme/issues/280.  Would welcome your feedback there.

**Comment by tupui** [comment]
What about using multiple columns?

**Comment by alphapapa** [comment]
> What about using multiple columns?

Good idea, I'll try that.  Thanks.

**Comment by alphapapa** [comment]
Just pushed a commit that uses a two-column layout, narrowing to one column on narrower screens.

<details><summary>Screenshots

</summary>
<p>

![localhost_1313_posts_ (1)](https://github.com/scientific-python/blog.scientific-python.org/assets/601365/86310ad3-eb0c-4936-bbe6-55de4fdeedeb)
![localhost_1313_posts_ (2)](https://github.com/scientific-python/blog.scientific-python.org/assets/601365/320e71dd-62a8-4bc2-9ac2-2a163b748d03)
![localhost_1313_posts_ (3)](https://github.com/scientific-python/blog.scientific-python.org/assets/601365/ed2adb35-cd34-40a1-a277-0b6342eb9c55)
![localhost_1313_posts_](https://github.com/scientific-python/blog.scientific-python.org/assets/601365/a96e4426-51ab-49e9-8870-60a83664fd4f)

</p>
</details> 

Let me know what you think.  Thanks.

@tupui @jarrodmillman @stefanv

**Comment by tupui** [comment]
Looks nice to me 👍

**Comment by stefanv** [comment]
I quite like the two column layout. The line separating groups of two is somewhat confusing, though, giving the impression that two blog posts are grouped, so I'd get rid of that.

**Comment by alphapapa** [comment]
After further changes, here's what it looks like now:

<details><summary>Details</summary>
<p>

![localhost_1313_posts_ (1)](https://github.com/scientific-python/blog.scientific-python.org/assets/601365/abae4d57-bd2a-4aba-adb1-72394f52695a)
![localhost_1313_posts_](https://github.com/scientific-python/blog.scientific-python.org/assets/601365/d9ff36bd-360f-49dd-a315-34e7ddb85d80)


</p>
</details> 

The post entries seemed a bit empty of text, which was especially jarring when adjacent posts shared the same image, so this returns the summaries, while using a smaller, yet still readable font.  This also allows the reader more context to decide whether the article would be of interest.  (Of course, the font is easily changed; there are numerous ones to choose from on https://fonts.google.com/  This seemed like a good balance of readability, aesthetics, and size.)

The individual article pages still need to be tidied slightly to correspond with the changes on the all-posts page.  I'll work on that next.

Please let me know what you think of these most recent changes.  Thanks.

**Comment by alphapapa** [comment]
After the latest changes (which includes https://github.com/scientific-python/scientific-python-hugo-theme/pull/289, a change to the theme repo), it looks like this (also visible on the deploy preview):

<details><summary>Front page, "All posts" page, individual post's page</summary>
<p>

![deploy-preview-137--blog-scientific-python-org netlify app_](https://github.com/scientific-python/blog.scientific-python.org/assets/601365/0c1f2e08-c1c1-4093-8cc1-6ed6a7d08299)
![deploy-preview-137--blog-scientific-python-org netlify app_posts_](https://github.com/scientific-python/blog.scientific-python.org/assets/601365/79d4c6fc-d9ad-4f0b-9562-e1d3b166ece0)
![deploy-preview-137--blog-scientific-python-org netlify app_scientific-python_dev-summit-1-development-guide_](https://github.com/scientific-python/blog.scientific-python.org/assets/601365/b6d87f9d-8fbe-41f7-bcb7-5d8eea942a3a)


</p>
</details> 

Included is a minor refactoring of the post list and adjustment to a partial template to allow an argument to toggle the post summary.

Please let me know what you think.  Thanks.

@jarrodmillman @stefanv @tupui
