### ISSUE TITLE
Fix post summaries and headers

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/blog.scientific-python.org#5]
![screenshot](https://user-images.githubusercontent.com/123428/156472398-20766168-135e-4a41-acf5-c8c351b6a6a0.png)

- [ ] date on on line
- [ ] how to handle code in summary (maybe require a short sentence summary as a field, maybe no summary)

**Comment by stefanv** [comment]
The date being next to the author was a conscious decision; would you prefer it be on the next line?

I see there are commas being rendered that should not be there.

**Comment by tupui** [comment]
I am for conciseness on the meta information to help on small screens. For the summary I also think it's needed especially when sharing an article, it should show the summary instead of a general description of the blog itself.

**Comment by stefanv** [comment]
@tupui @jarrodmillman Has all this been addressed to your liking?

For summaries in Hugo posts, there are several options:

- provide the summary as a field in the preamble
- add a marker into the text to separate the summary from the main text
- let Hugo guess what the summary is

See https://gohugo.io/content-management/summaries/#summary-splitting-options

**Comment by tupui** [comment]
I like the way it's on the website, what would be cool is to have the same information (with image) when you embed links (e.g. on Slack).

This is the current output
<img width="536" alt="Screenshot 2022-09-16 at 14 45 13" src="https://user-images.githubusercontent.com/23188539/190641726-a61a54d8-0979-45b5-ac00-56359970e889.png">

**Comment by stefanv** [comment]
@tupui Unless a `summary` field is given in the page header, the default site title will be displayed. So, all you need to do is to add that summary.  This holds for all sites that use the SP theme.

**Comment by stefanv** [comment]
I think we can close this then with the recommendation: write `summary` fields for all pages.

**Comment by tupui** [comment]
Ah ok, then yes we could update the archetype https://github.com/scientific-python/blog.scientific-python.org/blob/main/archetypes/default.md as well as the guidelines on how to write a post.

**Comment by stefanv** [comment]
Sorry, the field was `description`. Fixed in my comments above, and already correct in archetype.
