### ISSUE TITLE
tags clutter mobile layout

### ISSUE THREAD

**Issue by story645** [scientific-python/blog.scientific-python.org#56]
Hi, was wondering if the tags can be moved/hidden on mobile, cause they make the blog really hard to navigate.
![Screenshot_20220408-151857](https://user-images.githubusercontent.com/1300499/162509954-f5880e7f-e5a0-49a7-b5c5-54576d0b46c6.jpg)

**Comment by jarrodmillman** [comment]
I will take a look at fixing this next week (I have a ton of deadlines this weekend).  Of course, I am happy to review PRs as well (if someone gets to it first).

Here is how I added the existing tag cloud:
- https://github.com/scientific-python/blog.scientific-python.org/pull/44
