### ISSUE TITLE
Policy on modifying blogposts authored by others?

### ISSUE THREAD

**Issue by rossbar** [scientific-python/blog.scientific-python.org#82]
While reviewing #81 I came across the very nice blog post by Arseny Khakhalin on visualizing all graphs (in the network sense) with a certain number of nodes. When looking this over, I noticed it was very similar to the [graph atlas](https://networkx.org/documentation/latest/auto_examples/graphviz_layout/plot_atlas.html#sphx-glr-auto-examples-graphviz-layout-plot-atlas-py) from the networkx example gallery, so I thought it might be nice to add a cross-link to some of the NetworkX functionality that is related to the topic of the post.

However, I was unsure about what the policy is for non-authors making *content* modifications to others' blog posts. Certain modifications (grammar/formatting fixups, adding alt-text, etc.) should be uncontroversial as they don't really modify the content of the post. However, the posts have an `author` tag at the top which shows who wrote the original post. If someone *other* than the original author were to modify a post, then the author tag can make it seem like the modifier is putting words in the original author's mouth! Given this, I was wondering if there was a policy re: blog-post modification by non-authors.

**Comment by tupui** [comment]
Very interesting question. We could add an edited by section with a link to the history. The link to the history could actually be always present as we could have interesting discussions in the PR itself. It would also make it more "dev" like in the style. Depends how we present this information.

**Comment by jarrodmillman** [comment]
I would leave old blog posts as is. Maybe we could add a comment section though.

**Comment by stefanv** [comment]
See also #113

**Comment by stefanv** [comment]
We've added comments to blog posts now. Authors can modify their own posts, with a notice at the top, based on comments, if they want to.
